config/routes.rb
Rails.application.routes.draw do
  # トップページのルート
  root to: 'home#top'

  resources :traps, only: [:destroy]


  # 各ページへのルート設定
  get 'hunting_map', to: 'home#hunting_ground', as: :hunting_map
  get 'hunting_info', to: 'hunting#info', as: :hunting_info
  get 'trap_info', to: 'traps#index', as: :trap_info
  get 'request_board', to: 'requests#board', as: :request_board
  get 'hunter_list', to: 'hunters#list', as: :hunter_list
  get 'event_info', to: 'events#info', as: :event_info

  # Deviseのルート
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  # ユーザー一覧ページのルートを追加
  devise_scope :user do
    get 'users', to: 'users/registrations#index', as: 'user_list'
  end

  # ヘルスチェック
  get 'up', to: 'rails/health#show', as: :rails_health_check

  resources :trap_informations, only: [:index]

  # Trapsリソースのルート
  resources :traps, only: [:create, :index, :destroy] do
    collection do
      delete '', to: 'traps#destroy', as: :delete_by_coords
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/marker.rb
class Marker < ApplicationRecord
end

app/models/trap.rb
class Trap < ApplicationRecord
  belongs_to :user
  validates :lat, :lng, presence: true
  validates :trap_type, presence: true
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :traps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          # Deviseのemailバリデーションをオーバーライドして、必須にしない
          #  validates :email, presence: false
          #  validates :password, presence: true, length: { within: 6..128 }, confirmation: true
          #  validates :phone_number, presence: true, uniqueness: true
          #  validate :email_or_phone_number_present            
  
  # Deviseのメールアドレス認証をオーバーライド
  # def self.find_for_database_authentication(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if (login = conditions.delete(:login))
  #     where(conditions.to_h).where(["lower(phone_number) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  #   elsif conditions.key?(:phone_number) || conditions.key?(:email)
  #     where(conditions.to_h).first
  # end
# end

 attr_writer :login

 def login
   @login || self.phone_number || self.email
 end

#  class Hunter < User
#    # ハンター固有のメソッドやバリデーション
#  end

#  class Client < User
#    # クライアント固有のメソッドやバリデーション
# end

validates :email, presence: true


private

   def email_or_phone_number_present
     if email.blank? && phone_number.blank?
       errors.add(:base, "メールアドレスか電話番号のどちらかを入力してください")
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!, except: [:new, :create]
     before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :net_hunting_license, :trap_hunting_license, :first_class_hunting_license, :second_class_hunting_license])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :net_hunting_license, :trap_hunting_license, :first_class_hunting_license, :second_class_hunting_license])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :remember_me])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def info
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:top]



  def top
    flash[:notice] = "Welcome to the top page!"
  end
  
  def hunting_ground
    # 狩場ページのロジック
  end
end

app/controllers/hunters_controller.rb
class HuntersController < ApplicationController
  def list
  end
end

app/controllers/hunting_controller.rb
class HuntingController < ApplicationController
  def map
  end

  def info
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def board
  end
end

app/controllers/trap_informations_controller.rb
class TrapInformationsController < ApplicationController

  
    def index
      @traps = Trap.includes(:user).all
      render json: @traps.as_json(include: { user: { only: [:id, :name, :contact_information] } })
    end
  
   
  end
  

app/controllers/traps_controller.rb
class TrapsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_hunting_license, only: [:create]

 

    def create
      @trap = current_user.traps.build(trap_params)  # current_userに関連付けてトラップを作成
      # binding.irb
      if @trap.save
        render json: @trap.as_json(include: { user: { only: [:name, :contact_information] }  }), status: :created
      else
        render json: @trap.errors, status: :unprocessable_entity
      end
    end
  
    def index
       @traps = Trap.includes(:user).all # N+1問題を避けるためにincludesを使用
      end
  
    def destroy
      trap = Trap.find_by(id: params[:id]) # params[:id]を使用してIDを取得
      if trap  # @trapではなくtrapを使います
        trap.destroy
        head :no_content
      else
        render json: { error: "Trap not found" }, status: :not_found
      end
    rescue => e
      render json: { error: e.message }, status: :internal_server_error
    end
    

    private

    def check_hunting_license
      unless current_user.net_hunting_license || current_user.trap_hunting_license
        flash[:alert] = "トラップを設置するには網猟免許またはわな猟免許が必要です。"
        redirect_to root_path
      end
    end
  
    def trap_params
      params.require(:trap).permit(:lat, :lng, :trap_type, :start_date, :end_date)
    end
  end
  

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
    before_action :configure_sign_up_params, only: [:create]
  
    # ユーザー一覧を表示するアクション
    def index
      @users = User.all
    end
    
    protected
  
    # サインアップ時に許可するパラメータを追加
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :contact_information, :net_hunting_license, :trap_hunting_license, :first_class_hunting_license, :second_class_hunting_license])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hunters_helper.rb
module HuntersHelper
end

app/helpers/hunting_helper.rb
module HuntingHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/traps_helper.rb
module TrapsHelper
end

app/views/events/info.html.erb
<h1>Events#info</h1>
<p>Find me in app/views/events/info.html.erb</p>

app/views/home/hunting_ground.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>猟場MAP</title>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCA-vRsupZ3bq3ts8IibdEPp2TnJSCm094&callback=initMap"></script>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: { lat: 32.9736, lng: 131.5856 } // 豊後大野市の中心付近に設定
        });

        // 豊後大野市の境界を示すGeoJSONデータのURLを指定
        map.data.loadGeoJson('/city.json');

        // 境界線のスタイルを設定
        map.data.setStyle({
          strokeColor: '#FF0000', // 境界線の色
          strokeWeight: 2
        });

      // 自己位置を表示するための処理
      if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition, showError);
      } else {
        alert("Geolocation is not supported by this browser.");
      }

      function showPosition(position) {
        var userLat = position.coords.latitude;
        var userLng = position.coords.longitude;
        var userPosition = new google.maps.LatLng(userLat, userLng);

        // 地図をユーザーの位置に移動
        map.setCenter(userPosition);
        map.setZoom(15);

        // ユーザーの位置にマーカーを設定
        new google.maps.Marker({
          position: userPosition,
          map: map,
          title: "Your location"
        });
      }

      function showError(error) {
        switch (error.code) {
          case error.PERMISSION_DENIED:
            alert("User denied the request for Geolocation.");
            break;
          case error.POSITION_UNAVAILABLE:
            alert("Location information is unavailable.");
            break;
          case error.TIMEOUT:
            alert("The request to get user location timed out.");
            break;
          case error.UNKNOWN_ERROR:
            alert("An unknown error occurred.");
            break;
        }
      }
      }
    </script>
  </head>
  <body>
    <h1>猟場MAP</h1>
    <div id="map" style="height: 500px; width: 100%;"></div>
  </body>
</html>

app/views/home/top.html.erb
<main class="content">
<div id="carouselExampleFade" class="carousel slide carousel-fade">
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag 'ハンター.jpg', class: 'd-block w-100 carousel-image', alt: '風景' %>
    </div>
    <div class="carousel-item">
    <%= image_tag '風景.jpg', class: 'd-block w-100 carousel-image', alt: '風景' %>
    </div>
    <div class="carousel-item">
    <%= image_tag '農家.png', class: 'd-block w-100 carousel-image', alt: '農家' %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    <div class="hero-text">
      <h1>ハンター達と、地域を結ぶ。</h1>
    </div>
  </main>

  <style>
  .carousel-image {
    height: 500px; /* 高さを固定 */
    object-fit: cover; /* 画像を縦横比を保ちながらコンテナに収める */
  }
</style>

app/views/hunters/list.html.erb
<h1>Hunters#list</h1>
<p>Find me in app/views/hunters/list.html.erb</p>

app/views/hunting/info.html.erb
<h1>Hunting#info</h1>
<p>Find me in app/views/hunting/info.html.erb</p>

app/views/hunting/map.html.erb
<h1>Hunting#map</h1>
<p>Find me in app/views/hunting/map.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KariMee</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><%= image_tag 'logo2.png', alt: 'KariMee', class: 'logo-img' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if current_page?(hunting_map_path) %>">
            <%= link_to '狩場MAP', hunting_map_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(trap_info_path) %>">
            <%= link_to '罠情報', trap_info_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '登録者一覧', user_list_path, class: 'nav-link' %>
          </li>
            <li class="nav-item">
              <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-link nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <%= yield %>

  <footer>
    <p>&copy; 2024 KariMee</p>
  </footer>
</body>
</html>

app/views/requests/board.html.erb
<h1>Requests#board</h1>
<p>Find me in app/views/requests/board.html.erb</p>

app/views/traps/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Map with Traps</title>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCA-vRsupZ3bq3ts8IibdEPp2TnJSCm094&callback=initMap"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <script>
      var map;
      var traps = [];
      var infoWindow;

      function initMap() {
        // ユーザーの現在位置を取得
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var userLocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            if (!map) {
              map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: userLocation // ユーザーの現在位置をマップの中心に設定
              });
            }

            infoWindow = new google.maps.InfoWindow();

            // マップをクリックしたときにフォームを表示して、トラップを追加
            if (!map.hasListener) {
              map.addListener('click', function(event) {
                showTrapForm(event.latLng); 
              });
              map.hasListener = true; // フラグを設定
            }

            // 既存のトラップを読み込む
            loadTraps();

          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Geolocationが使用できない場合のエラー処理
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }

      function showTrapForm(location) {
        console.log("showTrapFormが呼び出されました");
        $('#trap-dialog').remove();
        $('#saveTrap').off('click');

        var formHtml = `
          <div>
            <label for="trapType">罠の種類を選択してください:</label><br>
            <select id="trapType">
              <option value="箱罠">箱罠</option>
              <option value="くくり罠">くくり罠</option>
            </select><br><br>

            <label for="startDate">設置開始日を選択してください:</label><br>
            <input type="text" id="startDate"><br><br>

            <label for="endDate">設置終了日を選択してください:</label><br>
            <input type="text" id="endDate"><br><br>

            <button id="saveTrap">罠を設置する</button>
          </div>
        `;

        var $dialog = $(formHtml).dialog({
          modal: true,
          title: "罠の設定",
          open: function() {
            $("#startDate, #endDate").datepicker({ dateFormat: 'yy-mm-dd', showOn: 'both', buttonText: 'カレンダーを表示'}); 
          },
          buttons: {
            "保存": function() {
              var trapType = $('#trapType').val();
              var startDate = $('#startDate').val();
              var endDate = $('#endDate').val();

              $(this).prop('disabled', true);
              var $button = $(this);
              $button.prop('disabled', true);

              // サーバーに保存してからマーカーを追加
              saveTrap(location.lat(), location.lng(), trapType, startDate, endDate)
                .then(data => {
                  console.log('Received data in saveTrap:', data); // ここでレスポンスデータを確認する

                  if (!data || !data.id) {
                    throw new Error('Invalid data received from server');
                  }
                // サーバーから返されるトラップのID
                const trapId = data.id;

                // ユーザーの情報
                const userName = data.user ? data.user.name : "Unknown";
                const contactInformation = data.user ? data.user.contact_information : "No contact info";
                
                addTrap(location, trapType, startDate, endDate, trapId, userName, contactInformation);
                })
                .catch(error => {
                  console.error('保存中に問題が発生しました:', error);
                 // alert('保存中に問題が発生しました: ' + error.message);
                })
                .finally(() => {
                  console.log("非同期処理が完了しました - ダイアログを閉じます");
                  $dialog.dialog("close"); // ダイアログを閉じる
                  $dialog.remove(); // ダイアログを破棄して完全に削除
                  console.log("ダイアログは正常に閉じられました");
                });
            },
            "キャンセル": function() {
              $dialog.dialog("close"); // キャンセル時にもダイアログを閉じる
              $dialog.dialog("destroy").remove(); // ダイアログを完全に削除
            }
          }
        });
        $('#saveTrap').off('click');
      }

      async function addTrap(location, trapType, startDate, endDate, trapId, userName, contactInformation) {
        try {
          var trap = new google.maps.Marker({
            position: location,
            map: map,
            icon: '/images/罠.png' // トラップを示すカスタムアイコンを設定
          });
          traps.push({ id: trapId, marker: trap });

          trap.addListener('click', function() {
            showTrapInfo(trap, trapId, trapType, startDate, endDate, userName);
          });
        } catch (error) {
          console.error('マーカーの追加中に異常が発生しました:', error);
        }
      }

      function showTrapInfo(trap, trapId, trapType, startDate, endDate, userName, contactInformation) {
        var lat = trap.getPosition().lat();
        var lng = trap.getPosition().lng();
        
        var contentString = `
          <div>
            <strong>トラップの位置</strong><br>
            設置者: ${userName}<br>
            連絡先: ${contactInformation}<br>
            緯度: ${lat}<br>
            経度: ${lng}<br>
            罠の種類: ${trapType}<br>
            設置期間: ${startDate} から ${endDate}<br><br>
            <button id="deleteTrap">罠を削除する</button>
          </div>
        `;

        infoWindow.setContent(contentString);
        infoWindow.open(map, trap);

        google.maps.event.addListenerOnce(infoWindow, 'domready', function() {
          document.getElementById("deleteTrap").addEventListener("click", function() {
            deleteTrap(trap, trapId);
          });
        });
      }

      function deleteTrap(trap, trapId) {
        console.log("Deleting Trap ID:", trapId);
        if (confirm("このトラップを削除しますか？")) {
          fetch(`/traps/${trapId}`, {
            method: 'DELETE',
            headers: {
              'Content-Type': 'application/json',
              'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            }
          })
          .then(response => {
            console.log("レスポンスステータス:", response.status);
            if (!response.ok) {
              return response.json().then(errorData => {
                throw new Error('Network response was not ok');
              });
            }
            if (response.status === 204) {
              console.log("削除が成功しましたが、レスポンスにはボディがありません。");
              google.maps.event.clearInstanceListeners(trap);
              trap.setMap(null); // ここでマーカーを削除
              location.reload(); // ページの完全リロード
              traps = traps.filter(t => t.marker !== trap); // 配列からも削除
              alert("トラップが削除されました。");
              return; // 204の場合、ここで処理を終了
            }
            google.maps.event.clearInstanceListeners(trap);
            trap.setMap(null);
            traps = traps.filter(t => t.marker !== trap);
            alert("トラップが削除されました。");
          })
          .catch(error => {
            console.error('There was a problem with the delete operation:', error);
            alert(`削除に失敗しました: ${error.message}`);
          });
        }
      }

      function loadTraps() {
        fetch('/trap_informations')
          .then(response => {
            console.log(response);
            if (response.headers.get('content-type')?.includes('application/json')) {
              return response.json();
            } else {
              throw new Error('Invalid JSON response');
            }
          })
          .then(data => {
      console.log('Traps data:', data);
      data.forEach(trapData => {
        if (!trapData.user || !trapData.user.name) {
          console.error('User data is missing for trap:', trapData);
        } else {
          const location = new google.maps.LatLng(trapData.lat, trapData.lng);
          const trapId = trapData.id;
          const trapType = trapData.trap_type;
          const startDate = trapData.start_date;
          const endDate = trapData.end_date;
          const userName = trapData.user.name;
          const contactInformation = trapData.user.contact_information;

          addTrap(location, trapType, startDate, endDate, trapId, userName, contactInformation);
        }
      });
    })
    .catch(error => {
      console.error('There was a problem with loading traps:', error);
    });
}
      
      async function addTrap(location, trapType, startDate, endDate, trapId, userName, contactInformation) {
        try {
          var trap = new google.maps.Marker({
            position: location,
            map: map,
            icon: '/images/罠.png'
          });
          traps.push({ id: trapId, marker: trap });
      
          trap.addListener('click', function() {
            showTrapInfo(trap, trapId, trapType, startDate, endDate, userName, contactInformation);
          });
        } catch (error) {
          console.error('マーカーの追加中に異常が発生しました:', error);
        }
      }
     
      function saveTrap(lat, lng, trapType, startDate, endDate, userName) {
        return fetch('/traps', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
          },
          body: JSON.stringify({ lat: lat, lng: lng, trap_type: trapType, start_date: startDate, end_date: endDate })
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          console.log('Received data in saveTrap:', data); // レスポンスデータを確認する
          if (!data || !data.id) {
            throw new Error('Invalid data received from server');
          }
      
          const trapId = data.id;
          const userName = data.user ? data.user.name : "Unknown";
          const contactInformation = data.user ? data.user.contact_information : "No contact info";
          
          // 保存後、マーカーを地図に追加する
          addTrap({ lat: lat, lng: lng }, trapType, startDate, endDate, trapId, userName, contactInformation);
        })
        .catch(error => {
          console.error('保存中に問題が発生しました:', error);
           alert('保存中に問題が発生しました: ' + error.message);
        });
      }

      document.addEventListener("DOMContentLoaded", function() {
        initMap();
        loadTraps();
      });
    
    </script>
  </head>
  <body>
    <h1>罠情報</h1>
    <div id="map" style="height: 500px; width: 90%;"></div>
  </body>
  </html>